"""empty message

Revision ID: ca8cea5e1e07
Revises: 
Create Date: 2025-04-10 19:41:39.895871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8cea5e1e07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_uid'), 'products', ['uid'], unique=False)
    op.create_table('properties',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_properties_name'), 'properties', ['name'], unique=False)
    op.create_index(op.f('ix_properties_uid'), 'properties', ['uid'], unique=False)
    op.create_table('product_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_uid', sa.String(), nullable=True),
    sa.Column('property_uid', sa.String(), nullable=True),
    sa.Column('value_uid', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_uid'], ['products.uid'], ),
    sa.ForeignKeyConstraint(['property_uid'], ['properties.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_properties_id'), 'product_properties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_properties_id'), table_name='product_properties')
    op.drop_table('product_properties')
    op.drop_index(op.f('ix_properties_uid'), table_name='properties')
    op.drop_index(op.f('ix_properties_name'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_products_uid'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
