"""empty message

Revision ID: df9ea93d06cc
Revises: ca8cea5e1e07
Create Date: 2025-04-10 19:50:10.466215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9ea93d06cc'
down_revision: Union[str, None] = 'ca8cea5e1e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_properties', sa.Column('value_str', sa.String(), nullable=True))
    op.add_column('product_properties', sa.Column('value_int', sa.Integer(), nullable=True))
    op.drop_column('product_properties', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_properties', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product_properties', 'value_int')
    op.drop_column('product_properties', 'value_str')
    # ### end Alembic commands ###
