version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog
    ports:
      - "5449:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/catalog
      PYTHONPATH: /app
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - custom

networks:
  custom:
    driver: bridge

#volumes:
#  postgres_data: